name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    env:
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to heroku
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a $HEROKU_APP web
      - name: Release
        run: heroku container:release -a $HEROKU_APP web
